/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Sat Sep 14 14:53:18 2019
#  Design:            mux4x1
#  Command:           saveNetlist mux4x1-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:29:52 IST (Sep 11 2019 20:59:52 UTC)
// Verification Directory fv/mux4x1 
module mux2x1 (
	S0, 
	x1, 
	x2, 
	m1);
   input S0;
   input x1;
   input x2;
   output m1;

   MX2X1 g23 (.A(x1),
	.B(x2),
	.S0(S0),
	.Y(m1));
endmodule

module mux2x1_1 (
	S0, 
	x1, 
	x2, 
	m1);
   input S0;
   input x1;
   input x2;
   output m1;

   MX2X1 g23 (.A(x1),
	.B(x2),
	.S0(S0),
	.Y(m1));
endmodule

module mux2x1_2 (
	S0, 
	x1, 
	x2, 
	m1);
   input S0;
   input x1;
   input x2;
   output m1;

   MX2X1 g23 (.A(x1),
	.B(x2),
	.S0(S0),
	.Y(m1));
endmodule

module mux4x1 (
	S0, 
	S1, 
	x1, 
	x2, 
	x3, 
	x4, 
	m1);
   input S0;
   input S1;
   input x1;
   input x2;
   input x3;
   input x4;
   output m1;

   // Internal wires
   wire int1;
   wire int2;

   mux2x1 A1 (.S0(S0),
	.x1(x1),
	.x2(x2),
	.m1(int1));
   mux2x1_1 A2 (.S0(S0),
	.x1(x3),
	.x2(x4),
	.m1(int2));
   mux2x1_2 A3 (.S0(S1),
	.x1(int1),
	.x2(int2),
	.m1(m1));
endmodule

