/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Sat Sep 14 16:03:34 2019
#  Design:            demux1x4
#  Command:           saveNetlist demux1x4-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:27:24 IST (Sep 11 2019 20:57:24 UTC)
// Verification Directory fv/demux1x4 
module demux1x2 (
	I1, 
	S0, 
	m1, 
	m2);
   input I1;
   input S0;
   output m1;
   output m2;

   NOR2BXL g17 (.AN(I1),
	.B(S0),
	.Y(m1));
   AND2X1 g18 (.A(S0),
	.B(I1),
	.Y(m2));
endmodule

module demux1x2_1 (
	I1, 
	S0, 
	m1, 
	m2);
   input I1;
   input S0;
   output m1;
   output m2;

   NOR2BXL g17 (.AN(I1),
	.B(S0),
	.Y(m1));
   AND2XL g18 (.A(S0),
	.B(I1),
	.Y(m2));
endmodule

module demux1x2_2 (
	I1, 
	S0, 
	m1, 
	m2);
   input I1;
   input S0;
   output m1;
   output m2;

   NOR2BXL g17 (.AN(I1),
	.B(S0),
	.Y(m1));
   AND2XL g18 (.A(S0),
	.B(I1),
	.Y(m2));
endmodule

module demux1x4 (
	I1, 
	S1, 
	S0, 
	m1, 
	m2, 
	m3, 
	m4);
   input I1;
   input S1;
   input S0;
   output m1;
   output m2;
   output m3;
   output m4;

   // Internal wires
   wire int1;
   wire int2;

   demux1x2 A1 (.I1(I1),
	.S0(S1),
	.m1(int1),
	.m2(int2));
   demux1x2_1 A2 (.I1(int1),
	.S0(S0),
	.m1(m1),
	.m2(m2));
   demux1x2_2 A3 (.I1(int2),
	.S0(S0),
	.m1(m3),
	.m2(m4));
endmodule

