
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:08:52 IST (Sep 11 2019 20:38:52 UTC)

// Verification Directory fv/demux1x2 

module demux1x2(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2XL g18(.A (S0), .B (I1), .Y (m2));
endmodule

