/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Sat Sep 14 20:43:55 2019
#  Design:            decoder1x2
#  Command:           saveNetlist decoder1x2-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:11:16 IST (Sep 11 2019 20:41:16 UTC)
// Verification Directory fv/decoder1x2 
module decoder1x2 (
	EN, 
	I1, 
	m1, 
	m2);
   input EN;
   input I1;
   output m1;
   output m2;

   NOR2BXL g17 (.AN(EN),
	.B(I1),
	.Y(m1));
   AND2XL g18 (.A(I1),
	.B(EN),
	.Y(m2));
endmodule

