
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:40:20 IST (Sep 11 2019 21:10:20 UTC)

// Verification Directory fv/priorityencoder3x8 

module priorityencoder3x8(EN, I1, I2, I3, I4, I5, I6, I7, I8, Y2, Y1,
     Y0);
  input EN, I1, I2, I3, I4, I5, I6, I7, I8;
  output Y2, Y1, Y0;
  wire EN, I1, I2, I3, I4, I5, I6, I7, I8;
  wire Y2, Y1, Y0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10;
  NAND2XL g223(.A (n_10), .B (n_9), .Y (Y1));
  OAI2BB1XL g224(.A0N (EN), .A1N (n_7), .B0 (n_10), .Y (Y0));
  OAI21XL g225(.A0 (n_4), .A1 (I7), .B0 (EN), .Y (n_9));
  NAND2XL g226(.A (n_10), .B (n_6), .Y (Y2));
  OAI21XL g227(.A0 (n_5), .A1 (I7), .B0 (n_3), .Y (n_7));
  OAI2BB1XL g229(.A0N (n_5), .A1N (n_2), .B0 (EN), .Y (n_6));
  NOR3XL g230(.A (I5), .B (I6), .C (n_0), .Y (n_4));
  OAI21XL g228(.A0 (n_1), .A1 (I4), .B0 (n_2), .Y (n_3));
  NOR2BXL g233(.AN (I2), .B (I3), .Y (n_1));
  NOR2XL g232(.A (I7), .B (I5), .Y (n_2));
  NOR2XL g231(.A (I4), .B (I3), .Y (n_0));
  NAND2XL g234(.A (I8), .B (EN), .Y (n_10));
  INVXL g235(.A (I6), .Y (n_5));
endmodule

