
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:34:45 IST (Sep 11 2019 21:04:45 UTC)

// Verification Directory fv/demux1x8 

module demux1x2_3(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2X1 g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x2(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2X1 g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x2_1(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2XL g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x2_2(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2XL g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x4(I1, S1, S0, m1, m2, m3, m4);
  input I1, S1, S0;
  output m1, m2, m3, m4;
  wire I1, S1, S0;
  wire m1, m2, m3, m4;
  wire int1, int2;
  demux1x2 A1(I1, S1, int1, int2);
  demux1x2_1 A2(int1, S0, m1, m2);
  demux1x2_2 A3(int2, S0, m3, m4);
endmodule

module demux1x2_4(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2X1 g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x2_5(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2XL g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x2_6(I1, S0, m1, m2);
  input I1, S0;
  output m1, m2;
  wire I1, S0;
  wire m1, m2;
  NOR2BXL g17(.AN (I1), .B (S0), .Y (m1));
  AND2XL g18(.A (S0), .B (I1), .Y (m2));
endmodule

module demux1x4_1(I1, S1, S0, m1, m2, m3, m4);
  input I1, S1, S0;
  output m1, m2, m3, m4;
  wire I1, S1, S0;
  wire m1, m2, m3, m4;
  wire int1, int2;
  demux1x2_4 A1(.I1 (I1), .S0 (S1), .m1 (int1), .m2 (int2));
  demux1x2_5 A2(.I1 (int1), .S0 (S0), .m1 (m1), .m2 (m2));
  demux1x2_6 A3(.I1 (int2), .S0 (S0), .m1 (m3), .m2 (m4));
endmodule

module demux1x8(I1, S2, S1, S0, m1, m2, m3, m4, m5, m6, m7, m8);
  input I1, S2, S1, S0;
  output m1, m2, m3, m4, m5, m6, m7, m8;
  wire I1, S2, S1, S0;
  wire m1, m2, m3, m4, m5, m6, m7, m8;
  wire int1, int2;
  demux1x2_3 A1(I1, S2, int1, int2);
  demux1x4 A2(int1, S1, S0, m1, m2, m3, m4);
  demux1x4_1 A3(int2, S1, S0, m5, m6, m7, m8);
endmodule

