
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:29:52 IST (Sep 11 2019 20:59:52 UTC)

// Verification Directory fv/mux4x1 

module mux2x1(S0, x1, x2, m1);
  input S0, x1, x2;
  output m1;
  wire S0, x1, x2;
  wire m1;
  MX2X1 g23(.A (x1), .B (x2), .S0 (S0), .Y (m1));
endmodule

module mux2x1_1(S0, x1, x2, m1);
  input S0, x1, x2;
  output m1;
  wire S0, x1, x2;
  wire m1;
  MX2X1 g23(.A (x1), .B (x2), .S0 (S0), .Y (m1));
endmodule

module mux2x1_2(S0, x1, x2, m1);
  input S0, x1, x2;
  output m1;
  wire S0, x1, x2;
  wire m1;
  MX2X1 g23(.A (x1), .B (x2), .S0 (S0), .Y (m1));
endmodule

module mux4x1(S0, S1, x1, x2, x3, x4, m1);
  input S0, S1, x1, x2, x3, x4;
  output m1;
  wire S0, S1, x1, x2, x3, x4;
  wire m1;
  wire int1, int2;
  mux2x1 A1(S0, x1, x2, int1);
  mux2x1_1 A2(S0, x3, x4, int2);
  mux2x1_2 A3(S1, int1, int2, m1);
endmodule

