
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 12 2019 02:11:16 IST (Sep 11 2019 20:41:16 UTC)

// Verification Directory fv/decoder1x2 

module decoder1x2(EN, I1, m1, m2);
  input EN, I1;
  output m1, m2;
  wire EN, I1;
  wire m1, m2;
  NOR2BXL g17(.AN (EN), .B (I1), .Y (m1));
  AND2XL g18(.A (I1), .B (EN), .Y (m2));
endmodule

